graph TD;
    A[Digital ID A]-->C[Tracking Event A]
    A[Digital ID A]-->E[Tracking Event B...]
    B[Digital ID B]-->F[Tracking Event A]
    B[Digital ID B]-->G[Tracking Event B]
    B[Digital ID B]-->H[Tracking Event C...]