sequenceDiagram
    participant TAM 
    participant Real Items Node 
    participant IPFS 
    participant Blockchain 
    TAM->>Real Items Node: Create n digital IDs
    loop For each digital ID 
        Real Items Node->>Real Items Node:  Create metadata 
        Real Items Node->>IPFS: Push metadata 
        IPFS->>IPFS: save metadata
        IPFS->>Real Items Node: return IPFS hash 
        Real Items Node->>Real Items Node:  Create NFT 
        Note right of IPFS: Transaction <br/>generated!
        Real Items Node->>Blockchain: store NFT 
    end
    Real Items Node-->>TAM: return receipt 