graph TD

    subgraph Client Layer
      subgraph Administrator 
        TAM[TAM]
      end
      subgraph Third-Party 
        THIRDPARTY[GraphQL API]
      end
      subgraph Proprietary Processes
        API[GraphQL API]
      end
      subgraph Logistics
        TRACKER[TRACKER]
      end
      subgraph End Consumer
        CP3[CP3]
      end
    end

    subgraph Real Items Oracle 
      RIO[RIO]
    end

    THIRDPARTY-->RIS
    API-->RIS
    TRACKER-->RIS
    RIO-->RIS
    CP3-->RIO

      subgraph Business Logic Layer
        RIS
      end
      subgraph Persistence Layer
        subgraph Mutable
          DB
        end
      subgraph Immutable
        IPFS[IPFS]
        BL[Blockchain]
       Analytic
      end
    end

    TAM[TAM]-->RIS[Real Items Server]
    RIS-->IPFS[IPFS]
    RIS-->BL[Blockchain]
    RIS-->DB[(Business Data)]
    RIS-->Analytic[(Analytics)]


